---
title: Main
timezone: UTC
collections:
  posts:
    title: page-2
    output: true
  uploads:
    title: Uploads
    output: true
theme: jekyll-theme-architect
baseurl: "/main" 
url: "https://discordtownofsalem.github.io/main"
